--- #Conditional playbook 
- hosts: all
  user: root 
  become: yes
  connection: ssh 
  tasks:
    - name: install apache2 for ubuntu
      command: apt-get -y install apache2
      when: ansible_distribution =="Ubuntu"
    - name: install apache for amazon linux
      command: yum -y install httpd
      when: ansible_distribution =="Amazon"  