---
- hosts: gpx 
  user: root 
  become: yes 
  connection: ssh
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Un-Install apache2
      apt:
        name: apache2
        state: absent
      notify: install_apache2

  handlers:
          - name: install_apache2
            apt:
              name: apache2
              state: latest        
