- name: install apache on debian
  command: apt-get -y install apache2
  when: ansible_distribution == "Ubuntu"

- name: install apache for redhat 
  command: yum -y install httpd  
  when: ansible_distribution == "Amazon"