---
- hosts: myHosts 
  user: root 
  become: yes 
  connection: ssh
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest 
    - name: "Check wheather app and database are running."
      script: appcheck.sh  
      args:
        executable: /bin/bash
      ignore_errors: true
      register: app_process_check
    - name: "Will check and start patching on linux servers"
      fail:
        msg: "{{ ansible_hostname }} have running Application. Please stop application and then proceed with patch."
      when: app_process_check.stdout == "Process is running."

