---
- hosts: myHosts 
  user: root 
  become: yes 
  connection: ssh
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest 
    - name: "Check wheather app and database are running."
      script: appcheck.sh  
      args:
        executable: /bin/bash
      ignore_errors: true
      register: app_process_check


